Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/debian-13"

  config.vm.provider "qemu" do |q|
    q.memory = 8192
    q.cpus = 4
  end

  config.vm.synced_folder "./confs", "/home/vagrant/confs", type: "rsync"

  config.vm.network "forwarded_port", guest: 8443, host: 8443 # ArgoCD
  config.vm.network "forwarded_port", guest: 8888, host: 8888 # App
  config.vm.network "forwarded_port", guest: 7777, host: 7777 # Gitlab

  config.vm.provision "shell", path: "./scripts/setup.sh"

end